name: Create Tag

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Determine Tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          echo "Latest Tag: $latest_tag"

      - name: Create Tag
        run: |
          git tag v1.0.0
          git push origin v1.0.0
        env:
          TOKEN: ${{ secrets.TOKEN }}
