name: Auto Tag on Commit

on:
  push:
    branches:
      - master  # Adjust branch if needed

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Determine Tag
        id: tag
        run: |
          # Get the latest tag
          latest_tag=$(git describe --tags --abbrev=0 || echo "v0.0.0")

          # Extract version parts
          IFS='.' read -r major minor patch <<<"${latest_tag//v/}"

          # Read commit message
          commit_message=$(git log -1 --pretty=%B)

          # Determine the next version based on commit message
          case "$commit_message" in
            CHORE:*) new_tag="v$((major+1)).0.0" ;;
            FEA:*) new_tag="v$major.$((minor+1)).0" ;;
            FIX:*) new_tag="v$major.$minor.$((patch+1))" ;;
            *) echo "No version change required"; exit 0 ;;
          esac

          echo "new_tag=$new_tag" >> $GITHUB_ENV

      - name: Create Tag
        run: |
          git tag ${{ env.new_tag }}
          git push origin ${{ env.new_tag }}
